apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloggingapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bloggingapp
  template:
    metadata:
      labels:
        app: bloggingapp
    spec:
      containers:
        - name: bloggingapp
          image: sairammuchintala/bloggingapp:latest  # Docker stage lo push chese image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred  # DockerHub secret (webapps namespace lo create chesi undali)
---
apiVersion: v1
kind: Service
metadata:
  name: bloggingapp-ssvc
spec:
  selector:
    app: bloggingapp
  ports:
    - protocol: TCP
      port: 80        # external service port
      targetPort: 8080  # containerPort
  type: LoadBalancer
