apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogging-app
  namespace: webapps
  labels:
    app: blogging-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blogging-app
  template:
    metadata:
      labels:
        app: blogging-app
    spec:
      containers:
        - name: blogging-app
          image: sairammuchintala/bloggingapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: blogging-app-service
  namespace: webapps
  labels:
    app: blogging-app
spec:
  type: LoadBalancer      # EKS lo external ELB kosam
  selector:
    app: blogging-app
  ports:
    - name: http
      port: 80            # external port
      targetPort: 8080    # containerPort above
